# Flyway Configuration File
flyway.url=jdbc:mysql://localhost:3306/kui?useSSL=false&allowPublicKeyRetrieval=true
flyway.user=root
flyway.password=admin
flyway.schemas=kui
flyway.locations=filesystem:sql
flyway.baselineOnMigrate=true
