# Flyway Configuration File
flyway.url=jdbc:mysql://localhost:3306/mms?useSSL=false&allowPublicKeyRetrieval=true
flyway.user=root
flyway.password=admin
flyway.schemas=mms
flyway.locations=filesystem:sql
flyway.baselineOnMigrate=true
