ALTER TABLE students ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE users ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE teachers ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL;
UPDATE students SET deleted_at = CURRENT_TIMESTAMP WHERE user_id IS NULL;
