ALTER TABLE students 
ADD COLUMN admission_year INT NULL,
ADD COLUMN dob DATE NULL,
ADD COLUMN father_name VARCHAR(255) NULL,
ADD COLUMN current_address TEXT NULL,
ADD COLUMN permanent_address TEXT NULL,
ADD COLUMN cnic VARCHAR(20) NULL,
ADD COLUMN identification_mark VARCHAR(255) NULL,
ADD COLUMN phone VARCHAR(20) NULL,
ADD COLUMN mobile VARCHAR(20) NULL,
ADD COLUMN email VARCHAR(100) NULL,
ADD COLUMN guardian_name VARCHAR(255) NULL,
ADD COLUMN guardian_father_name VARCHAR(255) NULL,
ADD COLUMN guardian_relationship VARCHAR(100) NULL,
ADD COLUMN guardian_cnic VARCHAR(20) NULL,
ADD COLUMN guardian_phone VARCHAR(20) NULL,
ADD COLUMN guardian_mobile VARCHAR(20) NULL,
ADD COLUMN religious_education VARCHAR(255) NULL,
ADD COLUMN religious_institution VARCHAR(255) NULL,
ADD COLUMN contemporary_education VARCHAR(255) NULL,
ADD COLUMN contemporary_board VARCHAR(255) NULL,
ADD COLUMN photo_url VARCHAR(255) DEFAULT '/images/default_student.png',
ADD COLUMN is_wifaq_registered TINYINT(1) DEFAULT 0,
ADD COLUMN wifaq_reg_number VARCHAR(100) NULL,
ADD COLUMN previous_madrasa_details TEXT NULL,
ADD COLUMN referral_source VARCHAR(255) NULL;
