name: Android Build & Deploy

on:
  push:
    branches:
      - mobile

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Build with Gradle
        run: |
          cd mobile
          chmod +x gradlew || true
          ./gradlew assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: mobile/app/build/outputs/apk/debug/app-debug.apk

      - name: Deploy APK to Server
        uses: appleboy/scp-action@master
        with:
          host: 185.217.127.114
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "mobile/app/build/outputs/apk/debug/app-debug.apk"
          target: "/var/www/kui-ms/public/"
          strip_components: 6 # Remove mobile/app/build/outputs/apk/debug/
          
      - name: Rename APK on Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 185.217.127.114
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            mv /var/www/kui-ms/public/app-debug.apk /var/www/kui-ms/public/kui.apk
            echo "APK deployed and accessible at https://kui.nukrim.com/mobile"
